import importlib.util
import sys
import tarfile
import tempfile
import unittest
from pathlib import Path


SCRIPT_DIR = (
    Path(__file__).resolve().parents[1]
    / "scripts"
)
SCRIPT_PATH = SCRIPT_DIR / "pesetech_make_addon.py"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
spec = importlib.util.spec_from_file_location("pesetech_make_addon", SCRIPT_PATH)
make_addon = importlib.util.module_from_spec(spec)
spec.loader.exec_module(make_addon)


class PesetechMakeAddonTest(unittest.TestCase):
    def test_make_addon_creates_self_contained_home_assistant_app(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            root = temp_path / "pesetech-home-assistant"
            output = temp_path / "ha-addon"
            (root / ".git").mkdir(parents=True)
            (root / ".git" / "config").write_text("secret git data", encoding="utf-8")
            (root / "docker" / "scripts").mkdir(parents=True)
            (root / "docker" / "config").mkdir(parents=True)
            (root / "scripts").mkdir(parents=True)
            (root / "gateway").mkdir(parents=True)
            (root / "requirements.txt").write_text("PyYAML==6.0\n", encoding="utf-8")
            (root / "README.md").write_text("readme\n", encoding="utf-8")
            (root / "docker" / "scripts" / "install-ell.sh").write_text("echo ell\n", encoding="utf-8")
            (root / "docker" / "scripts" / "install-json-c.sh").write_text("echo json\n", encoding="utf-8")
            (root / "docker" / "scripts" / "install-bluez.sh").write_text("echo bluez\n", encoding="utf-8")
            (root / "docker" / "config" / "config.yaml").write_text("mqtt:\n  password: secret\n", encoding="utf-8")
            (root / "scripts" / "pesetech_addon_config.py").write_text("# helper\n", encoding="utf-8")
            (root / "scripts" / "pesetech_addon_status.py").write_text("# status\n", encoding="utf-8")
            (root / "scripts" / "pesetech_verify_addon_package.py").write_text("# verifier\n", encoding="utf-8")
            (root / "gateway" / "gateway.py").write_text("# gateway\n", encoding="utf-8")

            addon_dir = make_addon.make_addon(root, output)

            self.assertEqual(addon_dir, (output / "pesetech_ble_mesh").resolve())
            self.assertTrue((output / "repository.yaml").exists())
            self.assertTrue((output / "README.md").exists())
            self.assertTrue((output / "INSTALL.md").exists())
            self.assertTrue((addon_dir / "Dockerfile").exists())
            self.assertTrue((addon_dir / "run.sh").exists())
            self.assertTrue((addon_dir / "source" / "gateway" / "gateway.py").exists())
            self.assertTrue((addon_dir / "source" / "scripts" / "pesetech_addon_config.py").exists())
            self.assertTrue((addon_dir / "source" / "scripts" / "pesetech_addon_status.py").exists())
            self.assertTrue((addon_dir / "source" / "scripts" / "pesetech_verify_addon_package.py").exists())
            self.assertFalse((addon_dir / "source" / ".git" / "config").exists())
            self.assertFalse((addon_dir / "source" / "docker" / "config" / "config.yaml").exists())

            config = (addon_dir / "config.yaml").read_text(encoding="utf-8")
            self.assertIn('slug: "pesetech_ble_mesh"', config)
            self.assertIn("  - aarch64", config)
            self.assertIn("  - amd64", config)
            self.assertNotIn("armv7", config)
            self.assertIn("full_access: true", config)
            self.assertIn("homeassistant_api: true", config)
            self.assertIn("services:\n  - mqtt:want", config)
            self.assertNotIn("usb: true", config)
            self.assertIn("  - type: share", config)
            self.assertIn("    read_only: false", config)
            self.assertNotIn("- share:rw", config)
            self.assertIn("mqtt_from_supervisor: true", config)
            self.assertIn('mqtt_from_supervisor: "bool"', config)
            self.assertIn(
                'operation: "list(service|runtime-check|mesh-daemon-check|ble-scan|status|preflight|scan|provision|configure|cloud-fetch|import-check|import|readiness-test|read-state|model-scope|raw-command|skylight-programs|move-test|ha-api-check|ha-service-test|proof-test|diagnostics|list)"',
                config,
            )
            self.assertIn('operation: "runtime-check"', config)
            self.assertNotIn('operation: "service"\n  mqtt_broker', config)
            self.assertIn("mqtt_port: 1883", config)
            self.assertIn('mqtt_port: "int(1,65535)"', config)
            self.assertIn('mesh_json_path: "/share/pesetech_mesh.json"', config)
            self.assertIn("import_mesh_candidate: 0", config)
            self.assertIn('import_mesh_candidate: "int(0,100)"', config)
            self.assertIn("import_force: false", config)
            self.assertIn('cloud_region: "europe"', config)
            self.assertIn('cloud_region: "list(asia|europe)"', config)
            self.assertIn('cloud_token: ""', config)
            self.assertIn('cloud_token: "password?"', config)
            self.assertIn('cloud_username: ""', config)
            self.assertIn('cloud_username: "str?"', config)
            self.assertIn('cloud_password: ""', config)
            self.assertIn('cloud_password: "password?"', config)
            self.assertIn('cloud_token_path: "/share/pesetech_cloud_token.txt"', config)
            self.assertIn('cloud_output_path: "/share/pesetech_mesh.json"', config)
            self.assertIn('cloud_report_path: "/share/pesetech_cloud_fetch_report.json"', config)
            self.assertIn('cloud_report_path: "str"', config)
            self.assertIn('cloud_candidate: "int(0,100)"', config)
            self.assertIn('cloud_home_id: ""', config)
            self.assertIn('cloud_home_id: "str?"', config)
            self.assertIn('ha_url: "http://supervisor/core"', config)
            self.assertIn('ha_entity_id: "light.skylight"', config)

            run_script = (addon_dir / "run.sh").read_text(encoding="utf-8")
            dockerfile = (addon_dir / "Dockerfile").read_text(encoding="utf-8")
            line_continuation = "\\" + "\n"
            self.assertIn("ARG BUILD_VERSION=0.1.0", dockerfile)
            self.assertIn("ARG BUILD_ARCH=amd64", dockerfile)
            self.assertIn('io.hass.version="${BUILD_VERSION}"', dockerfile)
            self.assertIn('io.hass.type="app"', dockerfile)
            self.assertIn('io.hass.arch="${BUILD_ARCH}"', dockerfile)

            self.assertIn("pesetech_addon_config.py", run_script)
            self.assertIn('if ! CONFIG_EXPORTS="$(python3 $APP_ROOT/scripts/pesetech_addon_config.py', run_script)
            self.assertIn('OPERATION_OVERRIDE_PATH="${OPERATION_OVERRIDE_PATH:-/share/pesetech_next_operation.json}"', run_script)
            self.assertIn('--override "$OPERATION_OVERRIDE_PATH"', run_script)
            self.assertIn("copy_report_to_share()", run_script)
            self.assertIn('copy_report_to_share "$DATA_DIR/pesetech-runtime-check.json" "pesetech-runtime-check.json"', run_script)
            self.assertIn('copy_report_to_share "$DATA_DIR/pesetech-mesh-daemon-check.json" "pesetech-mesh-daemon-check.json"', run_script)
            self.assertIn('copy_report_to_share "$PESETECH_MESH_SCAN_REPORT" "pesetech-mesh-scan.json"', run_script)
            self.assertIn('copy_report_to_share "$PESETECH_MESH_SCAN_TEXT" "pesetech-mesh-scan.txt"', run_script)
            self.assertIn('copy_report_to_share "$DATA_DIR/pesetech-import-check.json" "pesetech-import-check.json"', run_script)
            self.assertIn('copy_report_to_share "$DATA_DIR/pesetech-preflight.json" "pesetech-preflight.json"', run_script)
            self.assertIn('copy_report_to_share "$READINESS_REPORT" "pesetech-readiness.json"', run_script)
            self.assertIn('copy_report_to_share "$PROOF_LOG" "pesetech-move-test.jsonl"', run_script)
            self.assertIn('copy_report_to_share "$HA_PROOF_LOG" "pesetech-ha-service-proof.jsonl"', run_script)
            self.assertIn('copy_report_to_share "$FINAL_AUDIT_REPORT" "pesetech-final-audit.json"', run_script)
            self.assertIn("Failed to render add-on options; fix the app configuration and restart.", run_script)
            self.assertIn('eval "$CONFIG_EXPORTS"', run_script)
            self.assertIn('echo "Pesetech operation gate: $PESETECH_OPERATION"', run_script)
            self.assertIn("MQTT config source: Home Assistant Supervisor MQTT service.", run_script)
            self.assertIn("For workstation prove-ha-addon, use an externally reachable MQTT broker host", run_script)
            self.assertIn("MQTT config source: existing persisted $CONFIG_PATH.", run_script)
            self.assertNotIn('eval "$(python3 $APP_ROOT/scripts/pesetech_addon_config.py', run_script)
            self.assertIn("No gateway config found at $CONFIG_PATH. Set skylight_uuid for first-time service config", run_script)
            self.assertIn(
                '[ "$PESETECH_OPERATION" != "status" ] && [ "$PESETECH_OPERATION" != "cloud-fetch" ]',
                run_script,
            )
            self.assertIn('if [ "$PESETECH_OPERATION" = "runtime-check" ]', run_script)
            self.assertIn("write_runtime_report()", run_script)
            self.assertIn("pesetech_runtime_check.py", run_script)
            self.assertIn("pesetech-runtime-check.json", run_script)
            self.assertIn('"started_bluetooth_meshd": False', run_script)
            self.assertIn('if [ "$PESETECH_OPERATION" = "mesh-daemon-check" ]', run_script)
            self.assertIn("write_mesh_daemon_report()", run_script)
            self.assertIn("pesetech-mesh-daemon-check.json", run_script)
            self.assertIn('write_mesh_daemon_report "failed" "no hci* Bluetooth adapter was visible"', run_script)
            self.assertIn("Bluetooth Mesh daemon check passed.", run_script)
            self.assertIn("No provisioning, import, MQTT, or light-control commands were run.", run_script)
            self.assertIn('export PESETECH_MESH_SCAN_REPORT="$DATA_DIR/pesetech-mesh-scan.json"', run_script)
            self.assertIn('export PESETECH_MESH_SCAN_TEXT="$DATA_DIR/pesetech-mesh-scan.txt"', run_script)
            self.assertIn(
                'if python3 gateway.py --basedir "$DATA_DIR" --reload scan --seconds "$PESETECH_MESH_SCAN_SECONDS" --repeat "$PESETECH_MESH_SCAN_REPEAT" --stop-on-found; then',
                run_script,
            )
            self.assertIn('exit "$SCAN_EXIT"', run_script)
            self.assertIn('if [ "$PESETECH_OPERATION" = "ble-scan" ]', run_script)
            self.assertIn('BLE_SCAN_EXIT="$?"', run_script)
            self.assertIn('copy_report_to_share "$BLE_SCAN_REPORT" "pesetech-ble-scan.json"', run_script)
            self.assertIn('copy_report_to_share "$RAW_BLE_SCAN" "pesetech-ble-scan.txt"', run_script)
            self.assertIn("BLE scan completed: ", run_script)
            self.assertIn('tail -n 240 "$RAW_BLE_SCAN"', run_script)
            self.assertIn('exit "$BLE_SCAN_EXIT"', run_script)
            self.assertIn('if [ "$PESETECH_OPERATION" = "status" ]', run_script)
            self.assertIn("pesetech_addon_status.py", run_script)
            self.assertIn('--import-check-report "$DATA_DIR/pesetech-import-check.json"', run_script)
            self.assertIn('--runtime-report "$DATA_DIR/pesetech-runtime-check.json"', run_script)
            self.assertIn('--mesh-scan-report "$DATA_DIR/pesetech-mesh-scan.json"', run_script)
            self.assertIn('--ble-scan-report "$DATA_DIR/pesetech-ble-scan.json"', run_script)
            self.assertIn('--preflight-report "$DATA_DIR/pesetech-preflight.json"', run_script)
            self.assertIn('--ha-url "$PESETECH_HA_URL"', run_script)
            self.assertIn('--ha-entity-id "$PESETECH_HA_ENTITY_ID"', run_script)
            self.assertIn('--mqtt-source "$PESETECH_MQTT_SOURCE"', run_script)
            self.assertIn('--mqtt-broker "$PESETECH_MQTT_BROKER"', run_script)
            self.assertIn('--mqtt-port "$PESETECH_MQTT_PORT"', run_script)
            self.assertIn('--discovery-prefix "$PESETECH_DISCOVERY_PREFIX"', run_script)
            self.assertIn('--mesh-topic "$PESETECH_NODE_ID"', run_script)
            self.assertIn('--device-id "$PESETECH_DEVICE_ID"', run_script)
            self.assertIn('--import-mesh-candidate "$PESETECH_IMPORT_MESH_CANDIDATE"', run_script)
            self.assertIn('--import-node-uuid "$PESETECH_IMPORT_NODE_UUID"', run_script)
            self.assertIn('--import-node-unicast "$PESETECH_IMPORT_NODE_UNICAST"', run_script)
            self.assertIn('--import-local-address "$PESETECH_IMPORT_LOCAL_ADDRESS"', run_script)
            self.assertIn('STATUS_REPORT="$DATA_DIR/pesetech-status.json"', run_script)
            self.assertIn('SHARE_STATUS_REPORT="/share/pesetech-status.json"', run_script)
            self.assertIn('--output-json "$STATUS_REPORT"', run_script)
            self.assertIn("STATUS_EXIT=$?", run_script)
            self.assertIn('cp "$STATUS_REPORT" "$SHARE_STATUS_REPORT"', run_script)
            self.assertIn('exit "$STATUS_EXIT"', run_script)
            self.assertLess(
                run_script.index('if [ "$PESETECH_OPERATION" = "status" ]'),
                run_script.index("service dbus start"),
            )
            self.assertIn('if [ "$PESETECH_OPERATION" = "cloud-fetch" ]', run_script)
            self.assertIn("pesetech_fetch_cloud_mesh.py", run_script)
            self.assertIn('--output "$PESETECH_CLOUD_OUTPUT"', run_script)
            self.assertIn('--region "$PESETECH_CLOUD_REGION"', run_script)
            self.assertIn('--home-id "$PESETECH_CLOUD_HOME_ID"', run_script)
            self.assertIn('--report-output "$PESETECH_CLOUD_REPORT"', run_script)
            self.assertIn("write_inline_cloud_secret", run_script)
            self.assertIn("cleanup_cloud_secret_files() {", run_script)
            self.assertIn('if [ "${#CLOUD_SECRET_FILES[@]}" -gt 0 ]; then', run_script)
            self.assertIn('rm -f "${CLOUD_SECRET_FILES[@]}"', run_script)
            self.assertIn('target="$(mktemp "/tmp/${prefix}.XXXXXX")"', run_script)
            self.assertNotIn("cleanup_cloud_secret_files() {{", run_script)
            self.assertNotIn("${{#CLOUD_SECRET_FILES[@]}}", run_script)
            self.assertIn('if [ -n "$PESETECH_CLOUD_TOKEN" ]', run_script)
            self.assertIn("Using Pesetech cloud token from add-on configuration.", run_script)
            self.assertIn("Using Pesetech cloud username/password from add-on configuration.", run_script)
            self.assertIn('--token-file "$PESETECH_CLOUD_TOKEN_FILE"', run_script)
            self.assertIn('--username-file "$PESETECH_CLOUD_USERNAME_FILE"', run_script)
            self.assertIn('--cloud-report "$PESETECH_CLOUD_REPORT"', run_script)
            self.assertIn('--cloud-home-id "$PESETECH_CLOUD_HOME_ID"', run_script)
            self.assertIn("does not start D-Bus", run_script)
            self.assertIn("pesetech_cloud_report_summary.py", run_script)
            self.assertIn("CLOUD_FETCH_EXIT=$?", run_script)
            self.assertIn('if [ "$CLOUD_FETCH_EXIT" -ne 0 ]; then', run_script)
            self.assertIn('exit "$CLOUD_FETCH_EXIT"', run_script)
            self.assertLess(
                run_script.index("pesetech_cloud_report_summary.py"),
                run_script.index('if [ "$CLOUD_FETCH_EXIT" -ne 0 ]; then'),
            )
            self.assertLess(
                run_script.index('if [ "$PESETECH_OPERATION" = "cloud-fetch" ]'),
                run_script.index("service dbus start"),
            )
            self.assertIn('if [ "$PESETECH_OPERATION" = "preflight" ]', run_script)
            self.assertIn("write_preflight_report()", run_script)
            self.assertIn("pesetech-preflight.json", run_script)
            self.assertIn("pesetech_preflight.py " + line_continuation + '        --config "$CONFIG_PATH"', run_script)
            self.assertIn("pesetech_preflight.py", run_script)
            self.assertIn("--check-mqtt", run_script)
            self.assertEqual(run_script.count("--skip-docker"), 2)
            self.assertIn("/sys/class/bluetooth/hci*", run_script)
            self.assertIn("find_bluetooth_meshd()", run_script)
            self.assertIn("/usr/libexec/bluetooth/bluetooth-meshd", run_script)
            self.assertIn("/usr/lib/bluetooth/bluetooth-meshd", run_script)
            self.assertIn('if ! MESHD_BIN="$(find_bluetooth_meshd)"', run_script)
            self.assertIn('MESHD_ARGS=(--storage "$DATA_DIR/mesh-storage")', run_script)
            self.assertIn('"$MESHD_BIN" "${MESHD_ARGS[@]}" &', run_script)
            self.assertIn("MESHD_STARTUP_TIMEOUT", run_script)
            self.assertIn("an hci* adapter is available to the app", run_script)
            self.assertIn("prov --uuid", run_script)
            self.assertIn('if [ "$PESETECH_OPERATION" = "import-check" ]', run_script)
            self.assertIn("Validating mesh.json import plan without writing config or store.", run_script)
            self.assertIn("Existing imported gateway config and store found; import-check would not rewrite them", run_script)
            self.assertIn("Real import would skip and start the gateway service", run_script)
            self.assertIn('"${IMPORT_ARGS[@]}" --dry-run', run_script)
            self.assertIn('--report-output "$DATA_DIR/pesetech-import-check.json"', run_script)
            self.assertEqual(run_script.count('IMPORT_ARGS+=(--force)'), 3)
            self.assertIn("pesetech_import_telink_mesh.py", run_script)
            self.assertIn("--default-entity-id", run_script)
            self.assertEqual(run_script.count('IMPORT_ARGS+=(--mesh-candidate "$PESETECH_IMPORT_MESH_CANDIDATE")'), 3)
            self.assertIn("--node-uuid", run_script)
            self.assertIn("Existing imported gateway config and store found; skipping mesh.json import", run_script)
            self.assertIn('[ -s "$CONFIG_PATH" ] && [ -s "$DATA_DIR/store.yaml" ]', run_script)
            self.assertIn("readiness-test)", run_script)
            self.assertIn("Starting gateway for readiness-test. No light-control commands will be published.", run_script)
            self.assertIn('READINESS_REPORT="$DATA_DIR/pesetech-readiness.json"', run_script)
            self.assertIn('"sent_light_commands": False', run_script)
            self.assertIn("Readiness-test passed without publishing light-control commands.", run_script)
            self.assertIn("Wrote readiness report to $READINESS_REPORT.", run_script)
            self.assertIn("Keeping the gateway service running after readiness-test", run_script)
            self.assertIn("move-test)", run_script)
            self.assertIn("pesetech_mqtt_discovery.py", run_script)
            self.assertIn("pesetech_mqtt_smoke.py", run_script)
            self.assertIn("pesetech_verify_proof.py", run_script)
            self.assertIn("--allow-unobserved", run_script)
            self.assertIn("pesetech-move-test.jsonl", run_script)
            self.assertIn('rm -f "$PROOF_LOG"', run_script)
            self.assertIn("Writing a fresh move-test proof log", run_script)
            self.assertIn("ha-service-test)", run_script)
            self.assertIn("pesetech_ha_service_smoke.py", run_script)
            self.assertIn("pesetech_verify_ha_service_proof.py", run_script)
            self.assertIn("--require-mqtt-attributes", run_script)
            self.assertIn("pesetech-ha-service-proof.jsonl", run_script)
            self.assertIn("proof-test)", run_script)
            self.assertIn("pesetech-addon-", run_script)
            self.assertIn("pesetech_real_device_audit.py", run_script)
            self.assertIn('--proof-run-id "$PROOF_RUN_ID"', run_script)
            self.assertIn('rm -f "$PROOF_LOG" "$HA_PROOF_LOG" "$FINAL_AUDIT_REPORT"', run_script)
            self.assertIn('--output-json "$FINAL_AUDIT_REPORT"', run_script)
            self.assertIn("strict_visual_proof=false", run_script)
            self.assertIn("Logs share run id $PROOF_RUN_ID", run_script)
            self.assertIn("Keeping the gateway service running after proof-test", run_script)
            self.assertIn('wait "$GATEWAY_PID"', run_script)
            self.assertIn("No gateway config found at $CONFIG_PATH. Run provision or import before list.", run_script)
            self.assertIn('if [ "$PESETECH_OPERATION" = "ha-api-check" ]', run_script)
            self.assertIn("--check-api", run_script)
            self.assertIn("--check-entity", run_script)
            self.assertIn("Checking Home Assistant API/token before starting Bluetooth Mesh.", run_script)
            self.assertIn("--entity-timeout 30", run_script)
            self.assertIn('--candidate-search "${PESETECH_HA_ENTITY_ID#light.}"', run_script)
            self.assertLess(
                run_script.index('if [ "$PESETECH_OPERATION" = "ha-api-check" ]'),
                run_script.index("service dbus start"),
            )
            self.assertLess(
                run_script.index('if [ "$PESETECH_OPERATION" = "readiness-test" ] || [ "$PESETECH_OPERATION" = "ha-service-test" ] || [ "$PESETECH_OPERATION" = "proof-test" ]; then'),
                run_script.index("service dbus start"),
            )
            self.assertIn('if [ "$PESETECH_OPERATION" = "diagnostics" ]', run_script)
            self.assertIn("pesetech_diagnostics.py", run_script)
            self.assertIn("pesetech_diagnostics.py " + line_continuation + '        --config "$CONFIG_PATH"', run_script)
            self.assertNotIn("pesetech_diagnostics.py         --config", run_script)
            self.assertIn('--ha-proof-log "$DATA_DIR/pesetech-ha-service-proof.jsonl"', run_script)
            self.assertIn('--final-audit-report "$DATA_DIR/pesetech-final-audit.json"', run_script)
            self.assertIn('--readiness-report "$DATA_DIR/pesetech-readiness.json"', run_script)
            self.assertIn('--status-report "$DATA_DIR/pesetech-status.json"', run_script)
            self.assertIn('--runtime-report "$DATA_DIR/pesetech-runtime-check.json"', run_script)
            self.assertIn('--mesh-daemon-report "$DATA_DIR/pesetech-mesh-daemon-check.json"', run_script)
            self.assertIn('--preflight-report "$DATA_DIR/pesetech-preflight.json"', run_script)
            self.assertIn('--import-check-report "$DATA_DIR/pesetech-import-check.json"', run_script)
            self.assertIn('--import-mesh-candidate "$PESETECH_IMPORT_MESH_CANDIDATE"', run_script)
            self.assertIn("--live-discovery", run_script)
            self.assertIn('--ha-url "$PESETECH_HA_URL"', run_script)
            self.assertIn('--ha-entity-id "$PESETECH_HA_ENTITY_ID"', run_script)
            self.assertIn("--ha-api-context", run_script)
            self.assertIn('--ha-candidate-search "${PESETECH_HA_ENTITY_ID#light.}"', run_script)
            self.assertIn("--ha-require-mqtt-attributes", run_script)
            self.assertIn('--mqtt-source "$PESETECH_MQTT_SOURCE"', run_script)
            self.assertIn('--output-dir "$DIAG_OUTPUT_DIR"', run_script)
            self.assertIn("-d /share", run_script)
            self.assertIn("BLUETOOTH_ADAPTERS=(/sys/class/bluetooth/hci*)", run_script)
            self.assertIn("Bluetooth adapters visible to the app", run_script)
            self.assertIn("gateway.py --basedir", run_script)
            docs = (addon_dir / "DOCS.md").read_text(encoding="utf-8")
            self.assertIn("Supported Controls", docs)
            self.assertIn("runtime-check", docs)
            self.assertIn("mesh-daemon-check", docs)
            self.assertIn("cloud-fetch", docs)
            self.assertIn("/share/pesetech_mesh.json", docs)
            self.assertIn("import-check", docs)
            self.assertIn("import", docs)
            self.assertIn("service", docs)
            self.assertIn("Bluetooth adapter quality matters", docs)
            self.assertIn("Off-with-transition is unreliable", docs)
            self.assertNotIn("addon-runbook", docs)
            self.assertNotIn("proof-test", docs)
            self.assertNotIn("configuration_snippet", docs)
            self.assertLess(len(docs.splitlines()), 40)
            readme = (addon_dir / "README.md").read_text(encoding="utf-8")
            self.assertIn("Supported controls: on/off, brightness, color temperature", readme)
            self.assertIn("`runtime-check` -> `mesh-daemon-check` -> `cloud-fetch`", readme)
            self.assertIn("/share/pesetech_mesh.json", readme)
            self.assertIn("Keep defaults", readme)
            self.assertNotIn("addon-runbook", readme)
            self.assertNotIn("diagnostics", readme)
            self.assertLess(len(readme.splitlines()), 12)
            repository_readme = (output / "README.md").read_text(encoding="utf-8")
            self.assertIn("Generated Home Assistant add-on repository", repository_readme)
            self.assertIn("install `pesetech_ble_mesh`", repository_readme)
            self.assertIn("`runtime-check` -> `mesh-daemon-check` -> `cloud-fetch`", repository_readme)
            self.assertNotIn("addon-runbook", repository_readme)
            self.assertLess(len(repository_readme.splitlines()), 12)
            install = (output / "INSTALL.md").read_text(encoding="utf-8")
            self.assertIn("Git Repository Install", install)
            self.assertIn("Local `/addons` Install", install)
            self.assertIn("runtime-check", install)
            self.assertIn("mesh-daemon-check", install)
            self.assertIn("cloud-fetch", install)
            self.assertIn("/share/pesetech_mesh.json", install)
            self.assertIn("service", install)
            self.assertNotIn("addon-runbook", install)
            self.assertNotIn("HOME_ASSISTANT_TOKEN", install)
            self.assertLess(len(install.splitlines()), 30)
            changelog = (addon_dir / "CHANGELOG.md").read_text(encoding="utf-8")
            self.assertIn("Light CTL set arguments", changelog)
            self.assertIn("mesh-daemon-check operation", changelog)
            self.assertIn("status operation", changelog)
            self.assertIn("preflight report", changelog)
            self.assertIn("cloud-fetch operation", changelog)
            self.assertIn("direct add-on config credentials", changelog)
            self.assertIn("/api/hassio", changelog)
            self.assertIn("operation/log helper", changelog)
            self.assertIn("gate sequence helper", changelog)

            archive_path = temp_path / "pesetech-ha-addon.tar.gz"
            archive = make_addon.make_archive(output, archive_path)

            self.assertEqual(archive, archive_path.resolve())
            with tarfile.open(archive, "r:gz") as archive_file:
                names = set(archive_file.getnames())
            self.assertIn("repository.yaml", names)
            self.assertIn("README.md", names)
            self.assertIn("INSTALL.md", names)
            self.assertIn("pesetech_ble_mesh/config.yaml", names)
            self.assertIn("pesetech_ble_mesh/run.sh", names)
            self.assertIn(
                "pesetech_ble_mesh/source/scripts/pesetech_verify_addon_package.py",
                names,
            )
            self.assertNotIn("pesetech_ble_mesh/source/docker/config/config.yaml", names)
            self.assertNotIn("pesetech-ha-addon.tar.gz", names)

            local_archive_path = temp_path / "pesetech-ha-local-addon.tar.gz"
            local_archive = make_addon.make_local_archive(output, local_archive_path)

            self.assertEqual(local_archive, local_archive_path.resolve())
            with tarfile.open(local_archive, "r:gz") as archive_file:
                local_names = set(archive_file.getnames())
            self.assertIn("pesetech_ble_mesh/config.yaml", local_names)
            self.assertIn("pesetech_ble_mesh/run.sh", local_names)
            self.assertIn("pesetech_ble_mesh/source/scripts/pesetech_verify_addon_package.py", local_names)
            self.assertNotIn("repository.yaml", local_names)
            self.assertNotIn("README.md", local_names)
            self.assertNotIn("INSTALL.md", local_names)
            self.assertNotIn("pesetech_ble_mesh/source/docker/config/config.yaml", local_names)
            self.assertNotIn("pesetech-ha-local-addon.tar.gz", local_names)

    def test_make_addon_keeps_docker_label_default_version_in_sync(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir) / "pesetech-home-assistant"
            output = Path(temp_dir) / "ha-addon"
            (root / "scripts").mkdir(parents=True)
            (root / "requirements.txt").write_text("PyYAML==6.0\n", encoding="utf-8")
            (root / "scripts" / "pesetech_addon_config.py").write_text("# helper\n", encoding="utf-8")

            addon_dir = make_addon.make_addon(root, output, version="0.2.3")

            config = (addon_dir / "config.yaml").read_text(encoding="utf-8")
            dockerfile = (addon_dir / "Dockerfile").read_text(encoding="utf-8")
            self.assertIn('version: "0.2.3"', config)
            self.assertIn("ARG BUILD_VERSION=0.2.3", dockerfile)

    def test_make_addon_skips_output_folder_when_nested_under_source_root(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir) / "pesetech-home-assistant"
            output = root / "pesetech-ha-addon"
            (root / "scripts").mkdir(parents=True)
            (root / "requirements.txt").write_text("PyYAML==6.0\n", encoding="utf-8")
            (root / "scripts" / "pesetech_addon_config.py").write_text("# helper\n", encoding="utf-8")
            output.mkdir(parents=True)
            (output / "old.txt").write_text("old output", encoding="utf-8")

            addon_dir = make_addon.make_addon(root, output)

            self.assertFalse((addon_dir / "source" / "pesetech-ha-addon" / "old.txt").exists())

    def test_docker_entrypoint_resolves_bluetooth_meshd_path(self):
        entrypoint = (SCRIPT_DIR.parent / "docker" / "scripts" / "entrypoint.sh").read_text(encoding="utf-8")

        self.assertIn("find_bluetooth_meshd()", entrypoint)
        self.assertIn("/usr/libexec/bluetooth/bluetooth-meshd", entrypoint)
        self.assertIn("/usr/lib/bluetooth/bluetooth-meshd", entrypoint)
        self.assertIn('if ! MESHD_BIN="$(find_bluetooth_meshd)"', entrypoint)
        self.assertIn('"$MESHD_BIN" --storage /config/mesh-storage', entrypoint)


if __name__ == "__main__":
    unittest.main()
