name: Pesetech BLE Mesh Gateway
description: Control Pesetech/Lepu artificial skylights over Bluetooth Mesh.
version: 0.2.0
slug: pesetech_ble_mesh
url: https://github.com/hrdwdmrbl/pesetech-home-assistant
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
stage: experimental
services:
  - mqtt:need
host_network: true
udev: true
full_access: true
privileged:
  - NET_ADMIN
  - NET_RAW
  - SYS_ADMIN
  - SYS_RAWIO
apparmor: false
map:
  - type: share
    read_only: true
options: {}
schema: {}
